import { NavLink, Outlet } from 'react-router-dom'
import { BarChart3, BookOpen, BrainCircuit, ChevronRight, CircleUserRound, FileText, FlaskConical, LayoutDashboard, LogOut, Menu, Network, ShieldCheck, Users, X } from 'lucide-react'
import { useState } from 'react'
import type { User } from '../types'

const links = [{ to: '/admin', label: 'Overview', icon: LayoutDashboard, end: true }, { to: '/admin/industry-demand', label: 'Industry demand', icon: BarChart3 }, { to: '/admin/curriculum', label: 'Curriculum coverage', icon: BookOpen }, { to: '/admin/skill-gaps', label: 'Skill gaps', icon: Network }, { to: '/admin/students', label: 'Students', icon: Users }, { to: '/admin/course-generator', label: 'Course generator', icon: BrainCircuit }, { to: '/admin/course-history', label: 'Outline history', icon: FileText }, { to: '/try-it', label: 'Try It Live', icon: FlaskConical }]
export function AdminLayout({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [open, setOpen] = useState(false)
  return <div className="shell"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark">SB</div><div><strong>SkillBridge</strong><span>workforce intelligence</span></div><button className="icon-button mobile-close" onClick={() => setOpen(false)} aria-label="Close navigation"><X size={18} /></button></div><div className="sidebar-label">Command center</div><nav>{links.map(({ to, label, icon: Icon, end }) => <NavLink key={to} to={to} end={end} onClick={() => setOpen(false)}><Icon size={17} /><span>{label}</span><ChevronRight size={14} className="nav-arrow" /></NavLink>)}</nav><div className="sidebar-footer"><div className="account"><CircleUserRound size={19} /><div><b>{user.email.split('@')[0]}</b><span>Administrator</span></div></div><button className="logout" onClick={onLogout}><LogOut size={16} /> Sign out</button></div></aside><main className="main"><header className="topbar"><button className="icon-button mobile-menu" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><div className="crumb"><ShieldCheck size={17} /> Admin workspace</div><div className="topbar-right"><span className="live-dot" /> Live data <span className="topbar-divider" /> India focus</div></header><div className="page"><Outlet /></div></main></div>
}