import { useEffect, useState } from 'react'
import { ArrowRight, BookOpen, CheckCircle2, ExternalLink, Flag, PlayCircle, Route as RouteIcon } from 'lucide-react'
import { api } from '../api'
import type { Recommendation, RoadmapItem } from '../types'
import { Badge, Empty, ErrorState, Loading, SectionTitle } from '../components/UI'

export function RecommendationsPage() { const [items, setItems] = useState<Recommendation[] | null>(null); const [error, setError] = useState(''); const load = () => api.recommendations().then(r => setItems(r.items)).catch(e => setError(e.message)); useEffect(() => { load() }, []); if (error) return <ErrorState message={error} retry={load} />; if (!items) return <Loading />; return <><SectionTitle eyebrow="Learning resources" title="Learn what matters" description="Resources connected to the missing skills in your current target-role path." />{items.length ? <div className="resource-grid">{items.map((item, index) => <article className="panel resource-card" key={`${item.skill_id}-${item.resource_id ?? index}`}><div className="resource-icon"><BookOpen size={19} /></div><div className="resource-heading"><Badge tone="amber">{item.skill}</Badge>{item.level && <span>{item.level}</span>}</div><h3>{item.resource_name ?? 'Resource unavailable'}</h3>{item.platform && <p className="resource-provider">{item.platform} · {item.type}</p>}<p className="resource-reason">{item.reason}</p>{item.url ? <a className="button secondary" href={item.url} target="_blank" rel="noreferrer">Open resource <ExternalLink size={14} /></a> : <span className="muted">Learning resource not available in current dataset.</span>}</article>)}</div> : <section className="panel"><Empty>No learning recommendations yet. Select a target role first.</Empty></section>}</> }

export function RoadmapPage() { const [weeks, setWeeks] = useState<Array<{ week_number: number; items: RoadmapItem[] }> | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState<number | null>(null); const [saved, setSaved] = useState<number[]>([]); const load = () => api.roadmap().then(r => setWeeks(r.items)).catch(e => setError(e.message)); useEffect(() => { load() }, []); const update = async (item: RoadmapItem) => { if (item.resource_id === null) return; setSaving(item.resource_id); try { await api.updateProgress({ skill_id: item.skill_id, resource_id: item.resource_id, status: 'completed', week_number: item.week_number }); setSaved(current => current.includes(item.resource_id!) ? current : [...current, item.resource_id!]); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save progress.') } finally { setSaving(null) } }; if (error) return <ErrorState message={error} retry={load} />; if (!weeks) return <Loading />; return <><SectionTitle eyebrow="Learning roadmap" title="Your next steps" description="A backend-generated path through the resources matched to your current skill gaps." />{weeks.length ? <div className="roadmap"><div className="roadmap-line" />{weeks.map(week => <section className="roadmap-week" key={week.week_number}><div className="week-marker">W{week.week_number}</div><div className="panel week-panel"><div className="week-heading"><div><span className="eyebrow">Week {week.week_number}</span><h2>{week.items[0]?.skill ?? 'Learning step'}</h2></div><Badge>{week.items.length} resource{week.items.length === 1 ? '' : 's'}</Badge></div>{week.items.map(item => <div className="roadmap-resource" key={`${item.skill_id}-${item.resource_id}`}><div className="roadmap-resource-icon">{item.resource_id !== null && saved.includes(item.resource_id) ? <CheckCircle2 size={18} /> : <PlayCircle size={18} />}</div><div className="roadmap-resource-copy"><b>{item.resource_name ?? item.skill}</b><span>{item.platform ?? 'Dataset resource'} · {item.type ?? 'Practice'}</span><p>{item.practice}</p></div>{item.resource_id !== null ? <button className="button secondary small" disabled={saving === item.resource_id || saved.includes(item.resource_id)} onClick={() => update(item)}>{saved.includes(item.resource_id) ? 'Completed' : saving === item.resource_id ? 'Saving...' : 'Mark complete'}</button> : <span className="muted">No resource</span>}</div>)}</div></section>)}</div> : <section className="panel"><Empty>Choose a target role and identify a skill gap to build your roadmap.</Empty></section>}<div className="roadmap-footnote"><Flag size={16} /> Progress is saved to your student account. The backend does not estimate percentage completion.</div></> }
