import { FormEvent, useEffect, useState } from 'react'
import { ArrowRight, CheckCircle2, ChevronRight, Pencil, Target, UserRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import type { StudentProfile, StudentRole } from '../types'
import { Badge, Empty, ErrorState, Loading, Metric, SectionTitle } from '../components/UI'

export function StudentOverview() {
  const [profile, setProfile] = useState<StudentProfile | null>(null)
  const [gap, setGap] = useState<Awaited<ReturnType<typeof api.studentGap>> | null>(null)
  const [roadmap, setRoadmap] = useState<Awaited<ReturnType<typeof api.roadmap>> | null>(null)
  const [error, setError] = useState('')
  const load = () => Promise.all([api.studentProfile(), api.studentGap(), api.roadmap()]).then(([p, g, r]) => { setProfile(p); setGap(g); setRoadmap(r) }).catch(e => setError(e.message))
  useEffect(() => { load() }, [])
  if (error) return <ErrorState message={error} retry={load} />
  if (!profile || !gap || !roadmap) return <Loading label="Loading your growth path..." />
  const topGap = gap.items[0]
  if (!profile.target_role) return <><SectionTitle eyebrow="First step / Student onboarding" title="Set your direction" description="Choose your target role before SkillBridge builds your analysis." /><section className="panel onboarding-card"><div className="target-icon"><Target size={25} /></div><h2>Choose your target role to get your SkillBridge skill analysis.</h2><p className="muted">Your role connects your profile, assessment, skill gaps, recommendations, roadmap, and readiness score to real job demand.</p><Link className="button primary" to="/student/target-role">Choose target role <ArrowRight size={16} /></Link></section></>
  return <><div className="student-welcome"><div><span className="eyebrow">Your career path / India</span><h1>Keep moving,<br /><em>{profile.name.split(' ')[0]}.</em></h1><p>Your learning path is built from real industry demand and your current demonstrated skills.</p></div><div className="role-chip"><Target size={17} /><span>Target role<b>{profile.target_role ?? 'Choose a target role'}</b></span></div></div><div className="metric-grid student-metrics"><Metric label="Readiness score" value={gap.readiness_score === null ? 'â€”' : `${gap.readiness_score}`} detail="SkillBridge score" accent="student-number" /><Metric label="Skill gaps" value={gap.items.filter(item => item.gap_score > 0).length} detail="skills to strengthen" accent="accent-number" /><Metric label="Roadmap weeks" value={roadmap.items.length} detail="in your current path" /><Metric label="Profile skills" value={profile.skills ? profile.skills.split(',').filter(Boolean).length : 0} detail="self-declared" /></div><div className="student-grid"><section className="panel next-panel"><SectionTitle eyebrow="Your next move" title="Highest-priority gap" description="Start here for the biggest impact on your target role." />{topGap ? <div className="next-gap"><div className="priority-icon"><Target size={22} /></div><div className="next-gap-copy"><span className="eyebrow">{topGap.priority} priority</span><h3>{topGap.skill}</h3><p>Your score <b>{topGap.student_score}</b> Â· Industry demand <b>{Math.round(topGap.industry_requirement * 100)}%</b></p></div><Link className="button primary" to="/student/skill-gap">View skill gap <ArrowRight size={16} /></Link></div> : <Empty>No skill gaps yet. Choose a target role to begin.</Empty>}</section><section className="panel progress-panel"><SectionTitle eyebrow="Your path" title="Roadmap at a glance" action={<Link className="text-link" to="/student/roadmap">Open roadmap <ArrowRight size={14} /></Link>} />{roadmap.items.length ? <div className="mini-roadmap">{roadmap.items.slice(0, 4).map(week => <Link to="/student/roadmap" className="mini-week" key={week.week_number}><span>W{week.week_number}</span><b>{week.items[0]?.skill ?? 'Learning step'}</b><ChevronRight size={15} /></Link>)}</div> : <Empty>Set a target role to build your roadmap.</Empty>}</section></div><div className="student-actions"><Link to="/student/assessment" className="action-card"><div><ClipboardIcon /><b>Assess your skills</b><span>Measure what you know today</span></div><ArrowRight size={17} /></Link><Link to="/student/recommendations" className="action-card"><div><BookIcon /><b>Learn what matters</b><span>Resources matched to your gaps</span></div><ArrowRight size={17} /></Link><Link to="/student/readiness" className="action-card"><div><GaugeIcon /><b>Check readiness</b><span>See your role alignment</span></div><ArrowRight size={17} /></Link></div></>
}

export function StudentProfilePage() {
  const [profile, setProfile] = useState<StudentProfile | null>(null); const [editing, setEditing] = useState(false); const [form, setForm] = useState({ name: '', experience: '', certifications: '' }); const [error, setError] = useState(''); const [saved, setSaved] = useState(false)
  const load = () => api.studentProfile().then(p => { setProfile(p); setForm({ name: p.name, experience: p.experience, certifications: p.certifications }) }).catch(e => setError(e.message)); useEffect(() => { void load() }, [])
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await api.updateStudentProfile(form); await load(); setEditing(false); setSaved(true); setTimeout(() => setSaved(false), 2500) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save profile.') } }
  if (error) return <ErrorState message={error} retry={load} />; if (!profile) return <Loading />
  return <><SectionTitle eyebrow="My profile" title="Your starting point" description="Keep your learning context current. Your profile skills are self-declared until assessed." action={!editing && <button className="button secondary" onClick={() => setEditing(true)}><Pencil size={14} /> Edit profile</button>} />{saved && <div className="success-banner"><CheckCircle2 size={16} /> Profile updated</div>}<section className="panel profile-panel"><div className="profile-identity"><div className="avatar"><UserRound size={26} /></div><div><h2>{profile.name}</h2><p>{profile.email} Â· {profile.student_id}</p></div><Badge tone="success">Student</Badge></div>{editing ? <form className="profile-form" onSubmit={submit}><label>Name<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required /></label><label>Experience<textarea value={form.experience} onChange={e => setForm({ ...form, experience: e.target.value })} /></label><label>Certifications<textarea value={form.certifications} onChange={e => setForm({ ...form, certifications: e.target.value })} /></label><div className="form-actions"><button type="button" className="button secondary" onClick={() => setEditing(false)}>Cancel</button><button className="button primary">Save changes</button></div></form> : <div className="profile-details"><div><span>Degree</span><b>{profile.degree}</b></div><div><span>Department</span><b>{profile.department}</b></div><div><span>Year / semester</span><b>{profile.year} / {profile.semester}</b></div><div><span>Target role</span><b>{profile.target_role ?? 'Not selected'}</b></div><div className="full"><span>Self-declared skills</span><div className="skill-pills">{profile.skills.split(',').filter(Boolean).map(skill => <Badge key={skill}>{skill.trim()}</Badge>)}</div></div></div>}</section></>
}

export function TargetRolePage() { const [roles, setRoles] = useState<StudentRole[]>([]); const [selected, setSelected] = useState(''); const [required, setRequired] = useState<Awaited<ReturnType<typeof api.setTargetRole>>['required_skills']>([]); const [error, setError] = useState(''); const [saved, setSaved] = useState(false); const load = () => Promise.all([api.studentRoles(), api.studentProfile()]).then(async ([r, p]) => { setRoles(r.items); setSelected(p.target_role ?? ''); if (p.target_role) setRequired((await api.setTargetRole(p.target_role)).required_skills) }).catch(e => setError(e.message)); useEffect(() => { load() }, [])
  const save = async () => { if (!selected) return; try { const result = await api.setTargetRole(selected); setRequired(result.required_skills); setSaved(true) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save target role.') } }
  if (error) return <ErrorState message={error} retry={load} />; return <><SectionTitle eyebrow="Target role" title="Choose where you are going" description="Your target role determines the industry skills, gaps, and learning path we show you." /><div className="role-layout"><section className="panel role-picker"><div className="target-icon"><Target size={24} /></div><h2>What role are you preparing for?</h2><p className="muted">Choose from real job titles in the SkillBridge dataset.</p><label>Target role<select value={selected} onChange={e => { setSelected(e.target.value); setSaved(false) }}><option value="">Select a role</option>{roles.map(role => <option key={role.target_role} value={role.target_role}>{role.target_role} Â· {role.job_count} jobs</option>)}</select></label><button className="button primary" disabled={!selected} onClick={save}>Save target role <ArrowRight size={16} /></button>{saved && <div className="success-banner compact"><CheckCircle2 size={15} /> Target role saved</div>}</section><section className="panel role-evidence"><SectionTitle eyebrow="Industry signal" title={selected ? `${selected} requires` : 'Required skills'} description="Aggregated from the matching job postings." />{required.length ? <div className="required-list">{required.map(skill => <div key={skill.skill_id}><span>{skill.canonical_name}</span><b>{Math.round(skill.demand_score * 100)}%</b><small>{skill.jobs_requiring_skill} of matching jobs</small></div>)}</div> : <Empty>Select a role to see its required skills.</Empty>}</section></div></>
}

function ClipboardIcon() { return <span className="action-icon"><Target size={19} /></span> }
function BookIcon() { return <span className="action-icon"><ChevronRight size={19} /></span> }
function GaugeIcon() { return <span className="action-icon"><CheckCircle2 size={19} /></span> }
