import { FormEvent, useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, RotateCcw, Trophy } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import type { AssessmentAttempt, AssessmentQuestion } from '../types'
import { Badge, Empty, ErrorState, Loading, SectionTitle } from '../components/UI'

export function AssessmentPage() {
  const [questions, setQuestions] = useState<AssessmentQuestion[]>([]); const [answers, setAnswers] = useState<Record<string, string>>({}); const [latest, setLatest] = useState<AssessmentAttempt | null>(null); const [history, setHistory] = useState<AssessmentAttempt[]>([]); const [submitted, setSubmitted] = useState<AssessmentAttempt | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const load = () => Promise.all([api.assessment(), api.assessmentLatest(), api.assessmentHistory()]).then(([q, l, h]) => { setQuestions(q.items); setLatest(l); setHistory(h.items) }).catch(e => setError(e.message)); useEffect(() => { load() }, [])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (Object.keys(answers).length !== questions.length) { setError('Answer every question before submitting.'); return } setBusy(true); setError(''); try { const result = await api.submitAssessment(questions.map(q => ({ question_id: q.question_id, answer: answers[q.question_id] }))); const latestResult = await api.assessmentLatest(); setSubmitted(latestResult ?? result); setLatest(latestResult ?? result); const updatedHistory = await api.assessmentHistory(); setHistory(updatedHistory.items); setAnswers({}) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to submit assessment.') } finally { setBusy(false) } }
  if (error && !questions.length) return <ErrorState message={error} retry={load} />; if (!questions.length) return <Loading label="Loading assessment questions..." />
  if (submitted) return <AssessmentResult attempt={submitted} onRetake={() => setSubmitted(null)} />
  return <><SectionTitle eyebrow="Assessment" title="Measure your current skills" description="Answer from what you know today. Your results update your personal gap and readiness path." action={<span className="assessment-meta"><Clock3 size={15} /> {Object.keys(answers).length} / {questions.length} answered</span>} />{error && <div className="form-error assessment-error">{error}</div>}<form onSubmit={submit}><div className="assessment-progress"><span style={{ width: `${Object.keys(answers).length / questions.length * 100}%` }} /></div><div className="question-list">{questions.map((question, index) => <article className="panel question-card" key={question.question_id}><div className="question-number">{String(index + 1).padStart(2, '0')}</div><div className="question-body"><div className="question-meta"><Badge>{question.observed_skill}</Badge><span>{question.difficulty}</span></div><h3>{question.question}</h3><textarea aria-label={`Answer question ${index + 1}`} placeholder="Write your answer..." value={answers[question.question_id] ?? ''} onChange={e => setAnswers({ ...answers, [question.question_id]: e.target.value })} /></div></article>)}</div><div className="assessment-submit"><span>Results are scored by the backend and kept in your assessment history.</span><button className="button primary" disabled={busy}>{busy ? 'Scoring assessment...' : <>Submit assessment <ArrowRight size={16} /></>}</button></div></form>{history.length > 0 && <AssessmentHistory items={history} />}</>
}

function AssessmentResult({ attempt, onRetake }: { attempt: AssessmentAttempt; onRetake: () => void }) { const scores = attempt.skill_scores ?? []; return <><Link className="back-link" to="/student"> <ArrowLeft size={15} /> Back to overview</Link><div className="result-hero"><div><span className="eyebrow">Assessment complete / Version {attempt.version}</span><h1>Your results are in.</h1><p>Use this snapshot to focus your next learning steps.</p></div><div className="result-score"><span>Overall score</span><b>{attempt.total_score}</b><small>out of 100</small></div></div><section className="panel result-panel"><SectionTitle eyebrow="Skill breakdown" title="What you demonstrated" description="Assessment results are distinct from self-declared profile skills." /><div className="score-grid">{scores.map(score => <div className="score-card" key={score.skill_id}><span>{score.skill ?? `Skill ${score.skill_id}`}</span><b>{score.score}</b><Badge tone={score.level === 'Strong' || score.level === 'Good' ? 'success' : score.level === 'Beginner' ? 'danger' : 'amber'}>{score.level}</Badge></div>)}</div>{!scores.length && <Empty>No canonical skill scores were produced for this attempt.</Empty>}<button className="button primary" onClick={onRetake}><RotateCcw size={15} /> Retake assessment</button></section></> }

function AssessmentHistory({ items }: { items: AssessmentAttempt[] }) { return <section className="panel assessment-history"><SectionTitle eyebrow="History" title="Previous attempts" /><div className="history-table">{items.map(item => <div key={item.attempt_id}><span>Version {item.version}</span><b>{item.total_score}</b><small>{new Date(item.submitted_at).toLocaleString()}</small><CheckCircle2 size={15} /></div>)}</div></section> }
