import { useEffect, useState } from 'react'
import { ArrowRight, CheckCircle2, Info, ShieldCheck, Target, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import type { SkillGapItem } from '../types'
import { Badge, Empty, ErrorState, Loading, Metric, SectionTitle } from '../components/UI'

export function StudentGapPage() { const [data, setData] = useState<Awaited<ReturnType<typeof api.studentGap>> | null>(null); const [error, setError] = useState(''); const load = () => api.studentGap().then(setData).catch(e => setError(e.message)); useEffect(() => { load() }, []); if (error) return <ErrorState message={error} retry={load} />; if (!data) return <Loading />; return <><SectionTitle eyebrow="Personal skill gap" title="What to learn next" description="Your current demonstrated skills compared with the requirements of your target role." action={data.target_role ? <Badge tone="success">{data.target_role}</Badge> : undefined} /><div className="formula-banner"><Info size={17} /><span><b>How this works:</b> skill gap = 100 âˆ’ your score. Priority combines industry demand with skill deficiency. The backend remains the source of truth.</span></div>{data.items.length ? <div className="gap-cards">{data.items.map((item, index) => <GapCard item={item} rank={index + 1} key={item.skill_id} />)}</div> : <section className="panel"><Empty>Choose a target role to calculate your personal skill gap.</Empty><Link className="button primary" to="/student/target-role">Choose target role <ArrowRight size={16} /></Link></section>}</> }
function GapCard({ item, rank }: { item: SkillGapItem; rank: number }) { return <article className={`personal-gap-card ${item.priority === 'High' ? 'high' : ''}`}><div className="personal-gap-top"><span className="gap-rank">0{rank}</span><div><span className="eyebrow">{item.priority} priority</span><h3>{item.skill}</h3></div><Badge tone={item.priority === 'High' ? 'danger' : item.priority === 'Medium' ? 'amber' : 'neutral'}>{item.level}</Badge></div><div className="score-track"><span style={{ width: `${item.student_score}%` }} /><i style={{ left: `${item.student_score}%` }} /></div><div className="personal-gap-numbers"><span>Your score <b>{item.student_score}</b></span><span>Industry demand <b>{Math.round(item.industry_requirement * 100)}%</b></span><span>Gap <b className="coral-text">{item.gap_score}</b></span></div><div className="gap-action"><Target size={15} />{item.recommended_action}<Link to="/student/recommendations">See resources <ArrowRight size={14} /></Link></div></article> }

export function ReadinessPage() { const [readiness, setReadiness] = useState<Awaited<ReturnType<typeof api.studentReadiness>> | null>(null); const [gap, setGap] = useState<Awaited<ReturnType<typeof api.studentGap>> | null>(null); const [history, setHistory] = useState<Awaited<ReturnType<typeof api.assessmentHistory>> | null>(null); const [error, setError] = useState(''); const load = () => Promise.all([api.studentReadiness(), api.studentGap(), api.assessmentHistory()]).then(([r, g, h]) => { setReadiness(r); setGap(g); setHistory(h) }).catch(e => setError(e.message)); useEffect(() => { load() }, []); if (error) return <ErrorState message={error} retry={load} />; if (!readiness || !gap || !history) return <Loading />; const previous = history.items.length > 1 ? history.items[history.items.length - 2].total_score : null; const current = readiness.score; return <><SectionTitle eyebrow="Readiness" title="Your alignment, made visible" description="A transparent view of how your demonstrated skills align with your selected role." /><div className="readiness-layout"><section className="panel readiness-card"><div className="readiness-orbit"><div><span>SkillBridge</span><b>{current === null ? 'â€”' : current}</b><small>Readiness Score</small></div></div><h2>{readiness.target_role ?? 'No target role selected'}</h2><p>Your SkillBridge Readiness Score reflects your demonstrated alignment with the skills required for your selected role. It is not a hiring probability.</p>{previous !== null && current !== null ? <div className="change-note"><TrendingUp size={15} /> Latest assessment score: {current - previous >= 0 ? '+' : ''}{(current - previous).toFixed(1)} from the previous attempt</div> : <div className="change-note neutral"><Info size={15} /> No previous assessment available for comparison.</div>}</section><section className="panel readiness-breakdown"><SectionTitle eyebrow="Contribution" title="Where you stand" />{gap.items.length ? <div className="readiness-list">{gap.items.map(item => <div key={item.skill_id}><div><b>{item.skill}</b><span>{item.student_score} / 100</span></div><div className="readiness-bar"><span style={{ width: `${item.student_score}%` }} /></div><Badge tone={item.student_score >= 70 ? 'success' : 'amber'}>{item.level}</Badge></div>)}</div> : <Empty>Select a target role first.</Empty>}</section></div><div className="readiness-note"><ShieldCheck size={17} /><span>Calculated from the latest available assessment and your selected role's industry-required skills.</span></div></> }
